# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [ "vendor" ]


# Site settings
title : Points without Tangents
tagline: "No points actually."
email : j.scott.stout@gmail.com
highlighter: rouge
paginate: 5

description: > # this means to ignore newlines until "baseurl:"
  I have been known to write stuff ... but not lately.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gambits.org" # the base hostname & protocol for your site
twitter_username: skout23
github_username:  skout23

# Build settings
markdown: kramdown
